### ISSUE TITLE
Documentação da Sprint 12

### ISSUE THREAD

**Issue by matheusbmello** [unb-mds/2023.2_DeOlhoRS#90]
# Descrição
Documentar planejamento e resultados da Sprint 12.
# Objetivos
- [x] Criar página de planejamento da sprint
- [x] Escrever resultado na página acima
- [x] Criar página de resultados da sprint
- [x] Escrever sobre os resultados na página acima
- [x] Adicionar o caminho no MkDocs
# Responsáveis
@matheusbmello 
# Critérios de avaliação 
* Documentação confere na brach documentação

**Comment by vitorfleonardo** [comment]
A release foi documentada!
